### ISSUE TITLE
Lots of references to Irene's local vagrant instance

### ISSUE THREAD

**Issue by davidshq** [Yoast/fact-check#34]
:-)

**Comment by terw-dan** [comment]
Hi David, 
Thanks for creating an issue. 

This project started out as a side project on Irene's local machine, so there could be a reference still to her vagrant. However we tried to remove them all before putting the beta online. 
Can you give an example of where this is still referenced? It might be we overlooked something before publishing. 
Thanks.

**Comment by davidshq** [comment]
Do a search in factCheck-140.min.js

I see lots of references like this:

`/Users/Irene/vagrant-local/www/wordpress-default/public_html/wp-content/plugins/fact-check/node_modules/lodash/_root.js`

**Comment by terw-dan** [comment]
Thanks for your reply. 
We'll check the minified version in the next release
